### ISSUE TITLE
Error _faction undefined variable

### ISSUE THREAD

**Issue by Churrofighter** [1ncontinentia/Incon-Intel#1]
Hi, no matter what I do, I keep getting and getting these errors:

![32273890-9bec9846-bf04-11e7-9b19-b5aa7c45e340](https://user-images.githubusercontent.com/9594604/32890090-a13c0adc-cacd-11e7-9638-344d6853084b.png)

I have correctly set up the _asymSide and the _asymFaction in INT_setup.sqf. Using CUP Units by the way.

**Comment by 1ncontinentia** [comment]
Have you tried putting the OPF_F in quotation marks in the INT_setup.sqf? 

As in line 23: 
`_asymFaction = OPF_F;` -- change to `_asymFaction = "OPF_F"`? 

That could cause the issue you are having. Let me know if that works and if so, I'll make sure the file is updated.

**Comment by 1ncontinentia** [comment]
That being said, it's a while since I wrote the script and I no longer have access to Arma so you'll have to bear with me as I test through you.

**Comment by Churrofighter** [comment]
Yeah, it did the trick.
